# Drupal root path
root: 'web'

# Determine which packages to compile.
# A value of '*' means that all packages of the specified type will be treated.
packages:
  module: '*'
  theme: '*'

# File Extensions
extensions:
  scripts: '.js'
  styles: '.scss'

# Underscore skipping
skipUnderscoreFiles: true

# Configurations for modules
modules:
  # JS files source & destination directories.
  scripts:
    source: 'js'
    destination: 'js'
  # SCSS files source & destination directories.
  styles:
    source: 'scss'
    destination: 'css'

# Configurations for themes
themes:
  # Single Directory Components folder.
  # Minified CSS & JS will be generated in the same location as found SCSS & JS.
  components: 'components'
  # JS files source & destination directories.
  scripts:
    source: 'js'
    destination: 'js'
  # SCSS files source & destination directories.
  styles:
    source: 'scss'
    destination: 'css'